version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB=game_db
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
